### ISSUE TITLE
Bug in solving

### ISSUE THREAD

**Issue by Rizon87** [SebastienEveno/mckinseysolvegame#19]
I’m using an eco system that has a solution of 8 species, and the code gives me only 6.
That’s the one I’m using:

Species(name="Birds Nest Fern",
            calories_provided=5000,
            calories_needed=0,
            depth_range="1001-1400m",
            temperature_range="26-27.9",
            food_sources=[]),
Species(name="Black Magic",
            calories_provided=4100,
            calories_needed=0,
            depth_range="681-1000m",
            temperature_range="28-29.5",
            food_sources=[]),
Species(name="Fairy Inkcap",
            calories_provided=5250,
            calories_needed=0,
            depth_range="210-680m",
            temperature_range="29.6-32",
            food_sources=[]),
Species(name="Indigo Milkcap",
            calories_provided=5350,
            calories_needed=0,
            depth_range="1001-1400m",
            temperature_range="26-27.9",
            food_sources=[]),
Species(name="Lacy Tree Philodendron",
            calories_provided=4950,
            calories_needed=0,
            depth_range="1001-1400m",
            temperature_range="26-27.9",
            food_sources=[]),
Species(name="Puffball",
            calories_provided=5050,
            calories_needed=0,
            depth_range="681-1000m",
            temperature_range="28-29.5",
            food_sources=[]),
Species(name="Scarlet Star",
            calories_provided=4600,
            calories_needed=0,
            depth_range="210-680m",
            temperature_range="29.6-32",
            food_sources=[]),
Species(name="Tillys",
            calories_provided=4450,
            calories_needed=0,
            depth_range="681-1000m",
            temperature_range="28-29.5",
            food_sources=[]),
Species(name="Tree Fern",
            calories_provided=4900,
            calories_needed=0,
            depth_range="210-680m",
            temperature_range="29.6-32",
            food_sources=[]),
Species(name="Ashy Rat",
            calories_provided=1350,
            calories_needed=3950,
            depth_range="681-1000m",
            temperature_range="28-29.5",
            food_sources=["Black Magic"]),
Species(name="Bald Eagle",
            calories_provided=3000,
            calories_needed=2000,
            depth_range="1001-1400m",
            temperature_range="26-27.9",
            food_sources=["Black Brocket", "Pocket Gopher"]),
Species(name="Black Brocket",
            calories_provided=3200,
            calories_needed=4950,
            depth_range="1001-1400m",
            temperature_range="26-27.9",
            food_sources=["Indigo Milkcap"]),
Species(name="Chilla",
            calories_provided=2400,
            calories_needed=5750,
            depth_range="1001-1400m",
            temperature_range="26-27.9",
            food_sources=["Black Brocket", "Highland"]),
Species(name="Coyote",
            calories_provided=1350,
            calories_needed=2200,
            depth_range="681-1000m",
            temperature_range="28-29.5",
            food_sources=["Scarlet", "Forest", "Northern"]),
Species(name="Fox",
            calories_provided=1300,
            calories_needed=2500,
            depth_range="210-680m",
            temperature_range="29.6-32",
            food_sources=["Geoffroy", "Red", "Merida"]),
Species(name="Crowned",
            calories_provided=3100,
            calories_needed=1300,
            depth_range="681-1000m",
            temperature_range="28-29.5",
            food_sources=["Coyote"]),
Species(name="Culpeo",
            calories_provided=1850,
            calories_needed=2500,
            depth_range="1001-1400m",
            temperature_range="26-27.9",
            food_sources=["Hooded", "Highland"]),
Species(name="Dices",
            calories_provided=3200,
            calories_needed=5600,
            depth_range="1001-1400m",
            temperature_range="26-27.9",
            food_sources=["Indigo Milkcap"]),
Species(name="Forest",
            calories_provided=2050,
            calories_needed=4250,
            depth_range="681-1000m",
            temperature_range="28-29.5",
            food_sources=["Puffball"]),
Species(name="Geoffroy",
            calories_provided=2050,
            calories_needed=5900,
            depth_range="210-680m",
            temperature_range="29.6-32",
            food_sources=["Merida", "Lowland"]),
Species(name="Ginger",
            calories_provided=1400,
            calories_needed=2650,
            depth_range="681-1000m",
            temperature_range="28-29.5",
            food_sources=["Forest"]),
Species(name="Golden",
            calories_provided=2550,
            calories_needed=4550,
            depth_range="681-1000m",
            temperature_range="28-29.5",
            food_sources=["Tillys"]),
Species(name="Owl",
            calories_provided=2300,
            calories_needed=1400,
            depth_range="681-1000m",
            temperature_range="28-29.5",
            food_sources=["Scarlet", "Ginger"]),
Species(name="Green",
            calories_provided=4700,
            calories_needed=3700,
            depth_range="1001-1400m",
            temperature_range="26-27.9",
            food_sources=["Culpeo", "Yellow", "Bald Eagle", "Hooded", "Chilla", "Dices", "Black Brocket", "Highland", "Pocket Gopher"]),
Species(name="Highland",
            calories_provided=1000,
            calories_needed=3650,
            depth_range="1001-1400m",
            temperature_range="26-27.9",
            food_sources=["Birds Nest Fern", "Lacy Tree Philodendron"]),
Species(name="Hooded",
            calories_provided=2450,
            calories_needed=3550,
            depth_range="1001-1400m",
            temperature_range="26-27.9",
            food_sources=["Black Brocket", "Birds Nest Fern", "Lacy Tree Philodendron", "Dices", "Highland"]),
Species(name="Jaguar",
            calories_provided=1800,
            calories_needed=2600,
            depth_range="681-1000m",
            temperature_range="28-29.5",
            food_sources=["Golden"]),
Species(name="Lowland",
            calories_provided=3750,
            calories_needed=4900,
            depth_range="210-680m",
            temperature_range="29.6-32",
            food_sources=["Tree Fern", "Scarlet", "Fairy Inkcap"]),
Species(name="Merida",
            calories_provided=800,
            calories_needed=4450,
            depth_range="210-680m",
            temperature_range="29.6-32",
            food_sources=["Tree Fern", "Scarlet"]),
Species(name="Northern",
            calories_provided=1800,
            calories_needed=7000,
            depth_range="681-1000m",
            temperature_range="28-29.5",
            food_sources=["Puffball"]),
Species(name="Ocelot",
            calories_provided=2150,
            calories_needed=4050,
            depth_range="210-680m",
            temperature_range="29.6-32",
            food_sources=["Stripped"]),
Species(name="Falcon",
            calories_provided=2650,
            calories_needed=3300,
            depth_range="210-680m",
            temperature_range="29.6-32",
            food_sources=["Red"]),
Species(name="Pygmy",
            calories_provided=900,
            calories_needed=3000,
            depth_range="210-680m",
            temperature_range="29.6-32",
            food_sources=["Scarlet Star"]),
Species(name="Red",
            calories_provided=3250,
            calories_needed=4800,
            depth_range="210-680m",
            temperature_range="29.6-32",
            food_sources=["Tree Fern"]),
Species(name="Scarlet",
            calories_provided=1400,
            calories_needed=3500,
            depth_range="681-1000m",
            temperature_range="28-29.5",
            food_sources=["Forest", "Ashy Rat", "Black Magic"]),
Species(name="Solitary",
            calories_provided=3400,
            calories_needed=4100,
            depth_range="210-680m",
            temperature_range="29.6-32",
            food_sources=["Stripped"]),
Species(name="Stripped",
            calories_provided=3950,
            calories_needed=3150,
            depth_range="210-680m",
            temperature_range="29.6-32",
            food_sources=["Red", "Lowland", "Pygmy"]),
Species(name="Pocket Gopher",
            calories_provided=2400,
            calories_needed=8800,
            depth_range="1001-1400m",
            temperature_range="26-27.9",
            food_sources=["Birds Nest Fern", "Indigo Milkcap"]),
Species(name="Yellow",
            calories_provided=3700,
            calories_needed=4100,
            depth_range="1001-1400m",
            temperature_range="26-27.9",
            food_sources=["Birds Nest Fern"])

**Comment by SebastienEveno** [comment]
Hi,

Sorry for the inconvenience and thank you for your example. I will look into it this weekend or next week.

Sebastien

**Comment by SebastienEveno** [comment]
Hi @Rizon87,

Are you sure of your input data? Lowland and Merida have Scarlet as food source but Scarlet lives in another depth range. Did you mean Scarlet Star?

**Comment by Rizon87** [comment]
You’re absolutely right. My bad!
