### ISSUE TITLE
[Enhancement] Displaying the eating order for manual check.

### ISSUE THREAD

**Issue by jambsanchors** [SebastienEveno/mckinseysolvegame#32]
During our last issue you were able to resolve the use case successfully. And you posted during the thread the eating order which i think it is quite helpful for a manual check.

@SebastienEveno you have posted as per the below link

https://github.com/SebastienEveno/mckinseysolvegame/issues/29#issuecomment-2318569087

My enhancement request is the JSON response can be as follows:

{'species': ['Great White Shark', 'Blue Jellyfish', 'Green Sea Turtle', 'Loggerhead Sea Turtle', 'Lanternfish', 'Red Moss', 'Sea Lettuce', 'Shrimp']}

{"Great White Shark":{"eats":["Green Sea Turtle","Loggerhead Sea Turtle"]},"Blue Jellyfish":{"eats":["Red Moss","Sea Lettuce"]},"Green Sea Turtle":{"eats":["Lanternfish"]},"Loggerhead Sea Turtle":{"eats":["Blue Jellyfish"]},"Lanternfish":{"eats":["Shrimp"]},"Shrimp":{"eats":["Red Moss","Sea Lettuce"]}}

**Comment by SebastienEveno** [comment]
Hi @jambsanchors ,

I made the change in the code. Please upgrade your package to version 1.0.6.

You should see the following returned value:

```python
{
              'Great White Shark': {
                  'calories_needed': 0,
                  'calories_provided': 6000,
                  'eats': ['Green Sea Turtle', 'Loggerhead Sea Turtle']
                  },
              'Blue Jellyfish': {
                  'calories_needed': 0,
                  'calories_provided': 150,
                  'eats': ['Sea Lettuce', 'Red Moss']
                  }, 
              'Green Sea Turtle': {
                  'calories_needed': 0,
                  'calories_provided': 2275,
                  'eats': ['Lanternfish']
                  }, 
              'Loggerhead Sea Turtle': {
                  'calories_needed': 0,
                  'calories_provided': 2275,
                  'eats': ['Blue Jellyfish']
                  }, 
              'Lanternfish': {
                  'calories_needed': 0,
                  'calories_provided': 300,
                  'eats': ['Shrimp']
                  }, 
              'Red Moss': {
                  'calories_needed': 0,
                  'calories_provided': 775
                  }, 
              'Sea Lettuce': {
                  'calories_needed': 0,
                  'calories_provided': 775
                  }, 
              'Shrimp': {
                  'calories_needed': 0,
                  'calories_provided': 50,
                  'eats': ['Red Moss', 'Sea Lettuce']
                  }
          }
```

**Comment by jambsanchors** [comment]
Hello @SebastienEveno 
I was trying your latest release but an error occurred in the line:
Traceback (most recent call last):
  File "C:\Users\jambsanchors\Desktop\original13.py", line 87, in <module>
    result.to_json()
    ^^^^^^^^^^^^^^


--------------------------------
from mckinseysolvegame import Species

my_species = [
    Species(name="Red Moss",
            calories_provided=3000,
            calories_needed=0,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=[]),
    Species(name="Sea Fan",
            calories_provided=3500,
            calories_needed=0,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=[]),
    Species(name="Sea Lettuce",
            calories_provided=3000,
            calories_needed=0,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=[]),
    Species(name="Blue Jellyfish",
            calories_provided=4500,
            calories_needed=3000,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Sea Lettuce", "Red Moss"]),
    Species(name="Glass Squid",
            calories_provided=3850,
            calories_needed=3750,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Shrimp"]),
    Species(name="Great White Shark",
            calories_provided=6000,
            calories_needed=4250,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Green Sea Turtle", "Loggerhead Sea Turtle", "Lanternfish"]),
    Species(name="Green Sea Turtle",
            calories_provided=4400,
            calories_needed=3000,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Lanternfish", "Sea Lettuce", "Sea Urchin", "Spadefish"]),
    Species(name="Lanternfish",
            calories_provided=3300,
            calories_needed=2700,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Shrimp"]),
    Species(name="Loggerhead Sea Turtle",
            calories_provided=4400,
            calories_needed=4350,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Blue Jellyfish", "Lanternfish", "Sea Lettuce", "Spadefish", "Sea Urchin"]),
    Species(name="Sea Urchin",
            calories_provided=2100,
            calories_needed=3000,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Sea Fan", "Sea Lettuce"]),
    Species(name="Shrimp",
            calories_provided=2750,
            calories_needed=1450,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Red Moss", "Sea Lettuce"]),
    Species(name="Spadefish",
            calories_provided=2100,
            calories_needed=2400,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Sea Fan"]),
    Species(name="Swordfish",
            calories_provided=5250,
            calories_needed=3750,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Glass Squid", "Lanternfish", "Shrimp"])
]

from mckinseysolvegame import Solver

result = Solver.find_sustainable_food_chain(my_species)
result.to_json()

print(result.to_json())
-----------------------

kindly advise

**Comment by jambsanchors** [comment]
i corrected my script to the below 
`from mckinseysolvegame import Species

my_species = [
    Species(name="Red Moss",
            calories_provided=3000,
            calories_needed=0,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=[]),
    Species(name="Sea Fan",
            calories_provided=3500,
            calories_needed=0,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=[]),
    Species(name="Sea Lettuce",
            calories_provided=3000,
            calories_needed=0,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=[]),
    Species(name="Blue Jellyfish",
            calories_provided=4500,
            calories_needed=3000,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Sea Lettuce", "Red Moss"]),
    Species(name="Glass Squid",
            calories_provided=3850,
            calories_needed=3750,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Shrimp"]),
    Species(name="Great White Shark",
            calories_provided=6000,
            calories_needed=4250,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Green Sea Turtle", "Loggerhead Sea Turtle", "Lanternfish"]),
    Species(name="Green Sea Turtle",
            calories_provided=4400,
            calories_needed=3000,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Lanternfish", "Sea Lettuce", "Sea Urchin", "Spadefish"]),
    Species(name="Lanternfish",
            calories_provided=3300,
            calories_needed=2700,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Shrimp"]),
    Species(name="Loggerhead Sea Turtle",
            calories_provided=4400,
            calories_needed=4350,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Blue Jellyfish", "Lanternfish", "Sea Lettuce", "Spadefish", "Sea Urchin"]),
    Species(name="Sea Urchin",
            calories_provided=2100,
            calories_needed=3000,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Sea Fan", "Sea Lettuce"]),
    Species(name="Shrimp",
            calories_provided=2750,
            calories_needed=1450,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Red Moss", "Sea Lettuce"]),
    Species(name="Spadefish",
            calories_provided=2100,
            calories_needed=2400,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Sea Fan"]),
    Species(name="Swordfish",
            calories_provided=5250,
            calories_needed=3750,
            depth_range="0-10m",
            temperature_range="26.7-28.2",
            food_sources=["Glass Squid", "Lanternfish", "Shrimp"])
]

from mckinseysolvegame import Solver

Solver.find_sustainable_food_chain(my_species)
`
and its returning blank with no error.

can you advise ? @SebastienEveno

**Comment by SebastienEveno** [comment]
> i corrected my script to the below `from mckinseysolvegame import Species
> 
> my_species = [ Species(name="Red Moss", calories_provided=3000, calories_needed=0, depth_range="0-10m", temperature_range="26.7-28.2", food_sources=[]), Species(name="Sea Fan", calories_provided=3500, calories_needed=0, depth_range="0-10m", temperature_range="26.7-28.2", food_sources=[]), Species(name="Sea Lettuce", calories_provided=3000, calories_needed=0, depth_range="0-10m", temperature_range="26.7-28.2", food_sources=[]), Species(name="Blue Jellyfish", calories_provided=4500, calories_needed=3000, depth_range="0-10m", temperature_range="26.7-28.2", food_sources=["Sea Lettuce", "Red Moss"]), Species(name="Glass Squid", calories_provided=3850, calories_needed=3750, depth_range="0-10m", temperature_range="26.7-28.2", food_sources=["Shrimp"]), Species(name="Great White Shark", calories_provided=6000, calories_needed=4250, depth_range="0-10m", temperature_range="26.7-28.2", food_sources=["Green Sea Turtle", "Loggerhead Sea Turtle", "Lanternfish"]), Species(name="Green Sea Turtle", calories_provided=4400, calories_needed=3000, depth_range="0-10m", temperature_range="26.7-28.2", food_sources=["Lanternfish", "Sea Lettuce", "Sea Urchin", "Spadefish"]), Species(name="Lanternfish", calories_provided=3300, calories_needed=2700, depth_range="0-10m", temperature_range="26.7-28.2", food_sources=["Shrimp"]), Species(name="Loggerhead Sea Turtle", calories_provided=4400, calories_needed=4350, depth_range="0-10m", temperature_range="26.7-28.2", food_sources=["Blue Jellyfish", "Lanternfish", "Sea Lettuce", "Spadefish", "Sea Urchin"]), Species(name="Sea Urchin", calories_provided=2100, calories_needed=3000, depth_range="0-10m", temperature_range="26.7-28.2", food_sources=["Sea Fan", "Sea Lettuce"]), Species(name="Shrimp", calories_provided=2750, calories_needed=1450, depth_range="0-10m", temperature_range="26.7-28.2", food_sources=["Red Moss", "Sea Lettuce"]), Species(name="Spadefish", calories_provided=2100, calories_needed=2400, depth_range="0-10m", temperature_range="26.7-28.2", food_sources=["Sea Fan"]), Species(name="Swordfish", calories_provided=5250, calories_needed=3750, depth_range="0-10m", temperature_range="26.7-28.2", food_sources=["Glass Squid", "Lanternfish", "Shrimp"]) ]
> 
> from mckinseysolvegame import Solver
> 
> Solver.find_sustainable_food_chain(my_species) ` and its returning blank with no error.
> 
> can you advise ? @SebastienEveno

Are you using a Jupyter notebook? It should work.

Otherwise you can do:

```python
result = Solver.find_sustainable_food_chain(my_species)
```
then you can print that result with 

```python
print(result)
```

**Comment by jambsanchors** [comment]
Im using notepad++ to edit. 

Will try tomorrow and let you know.

Thank you @SebastienEveno

**Comment by jambsanchors** [comment]
Hello @SebastienEveno,

I tried running the script on command prompt, but it didn't work. However, when I ran it on Jupyter, it worked as expected. I believe having one script for all tools would make it more flexible for users, like in the older version. However, so far, it has served the job quite well.

thanks for your contineous support and dedication!


this issue is closed, the user is able to check manually the resolution.

**Comment by SebastienEveno** [comment]
> Hello @SebastienEveno,
> 
> I tried running the script on command prompt, but it didn't work. However, when I ran it on Jupyter, it worked as expected. I believe having one script for all tools would make it more flexible for users, like in the older version. However, so far, it has served the job quite well.
> 
> thanks for your contineous support and dedication!
> 
> this issue is closed, the user is able to check manually the resolution.

Hi @jambsanchors,

Thanks, I will think about it. Usually people use Python packages in jupyter notebooks/python files.

Let me know if you encounter any other issue with the package, and good luck for the test.

Best,
Sebastien
